name: Test

on: push

jobs:
  test_macos_dev96:
    name: Test exception on MacOS for dev96
    runs-on: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Docker
        run: |
            docker info

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install boto3 moto==1.3.16.dev96
            pip show boto3 moto docker
            pip install pytest

      - name: Test
        run: |
            pytest -sv

  test_macos_dev110:
    name: Test exception on MacOS for dev110
    runs-on: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Docker
        run: |
            docker info

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install boto3 moto==1.3.16.dev110
            pip show boto3 moto docker
            pip install pytest

      - name: Test
        run: |
            pytest -sv

  test_linux_dev96:
    name: Test exception on Linux for dev96
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Docker
        run: |
            docker info

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install boto3 moto==1.3.16.dev96
            pip show boto3 moto docker
            pip install pytest

      - name: Test
        run: |
            pytest -sv

  test_linux_dev110:
    name: Test exception on Linux for dev110
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Docker
        run: |
            docker info

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install boto3 moto==1.3.16.dev110
            pip show boto3 moto docker
            pip install pytest

      - name: Test
        run: |
            pytest -sv
