name: Test

on: [push]

jobs:
  test_macos_dev96:
    name: Test MacOS for dev96
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install boto3 moto[all]==1.3.16.dev96
            pip show boto3 moto docker
            pip install pytest

      - name: Test
        run: |
            pytest -sv test.py

  test_macos_dev110:
    name: Test MacOS for dev110
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install boto3 moto[all]==1.3.16.dev110
            pip show boto3 moto docker
            pip install pytest

      - name: Test
        run: |
            pytest -sv test.py

  test_macos_dev122:
    name: Test MacOS for dev122
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install boto3 moto[all]==1.3.16.dev122
            pip show boto3 moto docker
            pip install pytest

      - name: Test
        run: |
            pytest -sv test.py

  test_linux_dev96:
    name: Test Linux for dev96
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Verify Docker
        run: |
            docker info

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install boto3 moto[all]==1.3.16.dev96
            pip show boto3 moto docker
            pip install pytest

      - name: Test
        run: |
            pytest -sv test.py

  test_linux_dev110:
    name: Test Linux for dev110
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Verify Docker
        run: |
            docker info

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install boto3 moto[all]==1.3.16.dev110
            pip show boto3 moto docker
            pip install pytest

      - name: Test
        run: |
            pytest -sv test.py

  test_linux_dev122:
    name: Test Linux for dev122
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Verify Docker
        run: |
            docker info

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install boto3 moto[all]==1.3.16.dev122
            pip show boto3 moto docker
            pip install pytest

      - name: Test
        run: |
            pytest -sv test.py
