name: Test

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test_mac:
    # Name the Job
    name: Test exception on OSX
    # Set the type of machine to run on
    runs-on: macos-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install boto3 moto==1.3.16.dev110

      # Runs the test
      - name: Test
        run: |
            pytest -sv
