name: Test

on: push

jobs:
  test_mac:
    name: Test exception on OSX
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Docker
        run: |
            docker info

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install boto3 moto==1.3.16.dev110
            pip show boto3 moto docker
            pip install pytest

      - name: Test
        run: |
            pytest -sv
